name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test the application
      run: |
        python -m unittest discover

    - name: Build Docker image
      run: |
        docker build -t flask-app .

    - name: Push Docker image to DockerHub
      run: |
        echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
